# throw

throw用于抛出一个用户定义的异常

## 例子

```
try {if (1%2 == 1) throw "it is an odd"} catch(ex){print ex};
// output
"USER" : "it is an odd"

ex;
// output
"USER" : "it is an odd"
```

Copyright

**©2025 浙江智臾科技有限公司 浙ICP备18048711号-3**
